language: perl
perl:
  - "5.22"

matrix:
  fast_finish: true
  allow_failures:
    - env: USE_CPANFILE_SNAPSHOT=false CPAN_RESOLVER=metadb PERL_CARTON_PATH=$HOME/no-snapshot HARNESS_VERBOSE=1
    - env: USE_CPANFILE_SNAPSHOT=true COVERAGE=1
env:
  global:
    # Carton --deployment only works on the same version of perl
    # that the snapshot was built from.
    - DEPLOYMENT_PERL_VERSION=5.22
    - DEVEL_COVER_OPTIONS="-ignore,^local/"
    - PERL_CARTON_PATH=$HOME/local
    - CPAN_RESOLVER=snapshot

    - DOCKER_IMAGE_NAME=metacpan-web
  matrix:

    # Get one passing run with coverage and one passing run with Test::Vars
    # checks.  If run together they more than double the build time.
    - USE_CPANFILE_SNAPSHOT=false CPAN_RESOLVER=metadb PERL_CARTON_PATH=$HOME/no-snapshot HARNESS_VERBOSE=1  BUILD_DOCKER=no
    - USE_CPANFILE_SNAPSHOT=true BUILD_DOCKER=yes
    - USE_CPANFILE_SNAPSHOT=true COVERAGE=1  BUILD_DOCKER=no

before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init

  - mkdir -p ~/bin
  - printf '#!/bin/sh\n%s "$@" --warning=no-unknown-keyword\n' "$(which tar)" > ~/bin/tar
  - chmod +x ~/bin/tar
  - export PATH="$HOME/bin:$PATH"
  - npm install -g less js-beautify
  # Pre-install from backpan to avoid upgrade breakage.
  - cpanm -n http://cpan.metacpan.org/authors/id/M/ML/MLEHMANN/common-sense-3.6.tar.gz
  - cpanm -n App::cpm Carton

install:
  - cpan-install --coverage   # installs converage prereqs, if enabled
  - AUTHOR_TESTING=0 cpm install -L $PERL_CARTON_PATH --resolver $CPAN_RESOLVER

before_script:
  - coverage-setup

script:
  # Parallel tests seem to have Heisenfailures.  Disable for now.
  # - carton exec prove -lr -j$(test-jobs) t
  - carton exec prove -lr t

after_success:
  - coverage-report

services:
  - docker

## Build and push a docker image in production
deploy:
  - provider: script
    script:
      - deploy/build.sh
    on:
      branch: master
      condition: $BUILD_DOCKER = 'yes'
  - provider: script
    script:
      - deploy/push.sh
    on:
      branch: master
      condition: $BUILD_DOCKER = 'yes'

notifications:
  email:
    recipients:
      - olaf@wundersolutions.com
    on_success: change
    on_failure: always
  irc: "irc.perl.org#metacpan-infra

# Use newer travis infrastructure.
cache:
  directories:
    - local
