services:
  web-asset-build:
    build:
      context: .
      target: build-assets
    volumes:
      - './root:/build/root/'
      - 'assets:/build/root/assets/'
    command: ['./build-assets.mjs', '--watch']
  web-server:
    build:
      context: .
      target: develop
    volumes:
      - './:/app/'
      - 'assets:/metacpan-web/root/assets'
      - '/app/local'
    ports:
      - '8000:80'
    develop:
      watch:
        - path: ./cpanfile
          action: rebuild
volumes:
  assets:
