services:
  asset-build:
    build:
      context: .
      target: build-assets
    volumes:
      - './root:/build/root/'
      - 'assets:/build/root/assets/'
    command: ['./build-assets.mjs', '--watch']
  server:
    build:
      context: .
      target: develop
    volumes:
      - './:/metacpan-web/'
      - 'assets:/metacpan-web/root/assets'
      - '/metacpan-web/local'
    ports:
      - '8000:80'
volumes:
  assets:
