---
name: Build deployment container
on:
  push:
    branches:
      - prod
      - staging
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-22.04
    name: Docker Push
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build test image
      - uses: docker/build-push-action@v2
        with:
          tags: metacpan/metacpan-web:test
          target: test
          push: false
      - name: Run Perl tests
        run: docker run -i metacpan/metacpan-web:test
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: metacpan/metacpan-web:$GITHUB_SHA
