name: Update cpanfile.snapshot
on:
    schedule:
        - cron: "1 15 * * 0"
    workflow_dispatch:
jobs:
    update-dep:
        runs-on: "ubuntu-20.04"
        steps:
            - uses: actions/checkout@v2.3.4
            - name: Get cpm
              run: >
                  curl -sL -o $RUNNER_TEMP/cpm https://git.io/cpm;
                  chmod +x $RUNNER_TEMP/cpm
            - name: Install deps
              run: >
                  $RUNNER_TEMP/cpm
                  install
                  --cpanfile cpanfile
                  --resolver metacpan
                  --show-build-log-on-failure
                  --local-lib-contained=local
            - name: Install forced deps
              run: >
                  curl -sL https://cpanmin.us/ | perl -
                  --cpanfile cpanfile.forced
                  --showdeps --installdeps
                  -L local
                  -q
                  .
                  | $RUNNER_TEMP/cpm
                  install
                  --resolver metacpan
                  --show-build-log-on-failure
                  --local-lib-contained=local
                  --reinstall
                  -
            - name: Maybe update cpanfile.snapshot
              run: perl -Ilocal/lib/perl5 local/bin/carton
            - name: Create Pull Request
              id: cpr
              uses: peter-evans/create-pull-request@v3.8.2
              with:
                  token: ${{ secrets.METACPAN_BOT_TOKEN }}
                  commit-message: Update cpanfile.snapshot
                  title: Update cpanfile.snapshot
                  author: MetaCPAN Bot <bot@metacpan.org>
                  committer: MetaCPAN Bot <bot@metacpan.org>
                  body: |
                      Auto-generated by [create-pull-request][1]

                      [1]: https://github.com/peter-evans/create-pull-request
                  push-to-fork: metacpan-bot/metacpan-web
                  branch: update-cpanfile-snapshot
            - name: Enable Pull Request Automerge
              if: steps.cpr.outputs.pull-request-operation == 'created'
              uses: peter-evans/enable-pull-request-automerge@v1
              with:
                  token: ${{ secrets.METACPAN_BOT_TOKEN }}
                  pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
