name: Update cpanfile.snapshot
on:
  schedule:
    - cron: "1 15 * * 0"
  workflow_dispatch:
jobs:
  update-dep:
    runs-on: "ubuntu-20.04"
    steps:
      - name: Generate Auth Token
        id: auth-token
        uses: jamestrousdale/github-app-jwt-token@0.1.4
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - id: git-user
        name: Set up git user
        uses: haarg/setup-git-user@v1
        with:
          jwt: ${{ steps.auth-token.outputs.jwt }}
      - uses: actions/checkout@v3
        with:
          token: ${{ steps.auth-token.outputs.auth-token }}
      - name: Get cpm
        run: |
          curl -sL -o $RUNNER_TEMP/cpm https://git.io/cpm
          chmod +x $RUNNER_TEMP/cpm
      - name: Install Carton::Snapshot
        run: >
          $RUNNER_TEMP/cpm
          install
          Carton::Snapshot
          --resolver metacpan
          --show-build-log-on-failure
          --local-lib-contained=local
      - name: Install deps
        run: >
          perl -Ilocal/lib/perl5 $RUNNER_TEMP/cpm
          install
          --cpanfile cpanfile
          --resolver metacpan
          --show-build-log-on-failure
          --local-lib-contained=local
      - name: Install forced deps
        run: >
          curl -sL https://cpanmin.us/
          | perl -
          --cpanfile cpanfile.forced
          --showdeps --installdeps
          -L local
          -q
          .
          | $RUNNER_TEMP/cpm
          install
          --resolver metacpan
          --show-build-log-on-failure
          --local-lib-contained=local
          --reinstall
          -
      - name: Maybe update cpanfile.snapshot
        run: perl -Ilocal/lib/perl5 local/bin/carton
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ steps.auth-token.outputs.auth-token }}
          commit-message: Update cpanfile.snapshot
          title: Update cpanfile.snapshot
          author: ${{ steps.git-user.outputs.user-full }}
          committer: ${{ steps.git-user.outputs.user-full }}
          body: |
            [GitHub Action Run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
          branch: update-cpanfile-snapshot
